spring:
  application:
    name: notes-service
  data:
    mongodb:
      database: notes-service
      port: 27017
      host: localhost
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration